"""empty message

Revision ID: f854b7f68a98
Revises: 3347b18006e1
Create Date: 2021-06-21 12:45:51.359477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f854b7f68a98'
down_revision = '3347b18006e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_code')
    op.add_column('user_details', sa.Column('session', sa.String(length=1024), nullable=True))
    op.create_unique_constraint(None, 'user_details', ['session'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='unique')
    op.drop_column('user_details', 'session')
    op.create_table('verification_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='verification_code_pkey'),
    sa.UniqueConstraint('code', name='verification_code_code_key'),
    sa.UniqueConstraint('phone', name='verification_code_phone_key')
    )
    # ### end Alembic commands ###
